### ISSUE TITLE
Login not returns login response

### ISSUE THREAD

**Issue by senthilnathang** [vkosuri/PyHPALM#2]
while using the plugin it returns 200 response code but no login authentication returned

when tried to access any rest api (crud operations) it asks for 

 Authentication failed. Browser based integrations - to login append '?login-form-required=y' to the url you tried to access

**Comment by vkosuri** [comment]
@senthilnathang I am very busy with serveral tasks, If you need anyhelp please let me know.  I am going to create documentation by this weekend.

**Comment by vkosuri** [comment]
I have pushed some of commits into master with df67542159b438c062d8052badb759bd65a940ff

Let me know if you are still facing issues

**Comment by vkosuri** [comment]
@senthilnathang I have pushed some more commits into master, please check and let me know

**Comment by senthilnathang** [comment]
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    hp.login()
  File "/home/sen/github/py-hpalm/src/hpalm.py", line 85, in login
    lwssocookie = resp.headers['WWW-Authenticate']
  File "/home/sen/.local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'www-authenticate'

**Comment by vkosuri** [comment]
@senthilnathang could you please share you example code?

**Comment by senthilnathang** [comment]
from src.hpalm import HPALM
#~ domain='test'
#~ project='test'
#~ base_url = "http://10.11.200.1:8080"
#~ username ="vkosuri"
#~ password="pass@007"
username='bornspy@gmail.com'
password='Zse4$rfV'
base_url ='https://almalm1250saastrial.saas.hpe.com/qcbin/'
domain='DEFAULT_773497139'
project='773497139_DEMO'
hp=HPALM(base_url=base_url,username=username,password=password,domain=domain,project=project)
hp.login()
hp.logout()

**Comment by vkosuri** [comment]
@senthilnathang I have pushed some more commits to solve your issue.

Now could try like this

```Python
from src.hpalm import HPALM

domain='test'
project='test'
base_url = "https://test-almhp:8080"
username ="vkosuri"
password="pass@007"
hp=HPALM(base_url=base_url,username=username,password=password,domain=domain,project=project, verify=False)
hp.login()
hp.logout()
```

**Comment by senthilnathang** [comment]
still it fails 

i have tried using this code working fine for login but not able to authenticate and access defects or test through rest api can you please check what i m missing here

import requests
session = requests.session()
username='bornspy@gmail.com'
password='Zse4$rfVa'
base_url ='https://almalm1250saastrial.saas.hpe.com/qcbin/'
domain='DEFAULT_773497139'
project='773497139_DEMO'
r = session.get(base_url+"authentication-point/authenticate",auth=(username,password))
headers = {'Content-Type' : 'application/xml'}
print r,"login"
print (r.text)
r=requests.put(base_url + u'/rest/domains/'+domain+u'/projects/'+project+'/defects', headers=headers, auth=(username,password))
print r
print r.text
r = session.get('http://almalm1250saastrial.saas.hpe.com/qcbin/rest/domains/'+domain+u'/projects/'+project)
print(r.text)

headers = {'Content-Type' : 'application/xml'}
authurl = base_url + '/qcbin/rest/is-authenticated'
resp = requests.get(authurl, headers=headers)
lwssocookie = resp.headers['WWW-Authenticate']
headers = {'Cookie' : lwssocookie}
headers["Accept"] = 'application/xml'
login_url = base_url + '/qcbin/authentication-point/authenticate'
resp = requests.get(login_url, headers=headers, auth=HTTPBasicAuth(username, password))
qc_session = resp.headers['Set-Cookie']  
cookie = ";".join((lwssocookie, qc_session))
headers = {'content-type' : 'application/xml'}
headers['accept'] = 'application/xml'
headers['cookie'] = cookie
if resp.status_code == 200:
    print "%s  %s logged into alm" %(resp.status_code, username)
else:
    print "%s  %s failed to logging into HP ALM" %(resp.status_code, username)           
print resp.status_code

**Comment by vkosuri** [comment]
I have tried your snippet on machine it working fine.

``` Bash
>>> from src.hpalm import HPALM
>>> 
>>> domain='DEFAULT_773497139'
>>> project='773497139_DEMO'
>>> base_url = "http://almalm1250saastrial.saas.hpe.com"
>>> username ="bornspy@gmail.com"
>>> password="Zse4$rfV"
>>> hp=HPALM(base_url=base_url,username=username,password=password,domain=domain,project=project)
>>> hp.login()
/home/developer/py-hpalm/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/developer/py-hpalm/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
/home/developer/py-hpalm/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/developer/py-hpalm/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
/home/developer/py-hpalm/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/developer/py-hpalm/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
/home/developer/py-hpalm/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
200
>>> hp.getheaders()
{'cookie': 'LWSSO realm="http://almalm1250saastrial.saas.hpe.com:80/qcbin/authentication-point";JSESSIONID=B4D1A71629DFBAB633596A6507F1FC80; Path=/msg/; HttpOnly, BIGipServerMSGAST01P=2982666255.20480.0000; path=/', 'content-type': 'application/xml', 'accept': 'application/xml'}
>>> 

```

**Comment by senthilnathang** [comment]
is it a version issue with request library (i m using 2.1.13)?

**Comment by vkosuri** [comment]
No, I think i am using latest version, can you try to clone fresh copy of this repository and install all required packages, if still producing same issue let me know. It is working fine in machine.

**Comment by senthilnathang** [comment]
sure will try thanks

**Comment by vkosuri** [comment]
@senthilnathang I can reproduce your problem on machine. The server returns always 404 becuase you don't have privileges to access perticuler domain. If you have correct privileges the server should return [LWSSO ](http://helpfiles.intactcloud.com/AM/9.30/administration/ch12s07se09.html) cookie to go further.

The current approach uses **Non-Web Application Authentication with Basic Authorization Header** For More information http://alm-help.saas.hpe.com/en/12.20/api_refs/REST_TECH_PREVIEW/ALM_REST_API_TP.html 

The response i have captured from your serer

``` HTTP
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 401 Authentication failed. Browser based integrations - to login append '?login-form-required=y' to the url you tried to access.</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /qcbin/rest/is-authenticated. Reason:
<pre>    Authentication failed. Browser based integrations - to login append '?login-form-required=y' to the url you tried to access.</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
```

**Comment by senthilnathang** [comment]
tried cloning latest and login method return cookie error with ['www-authenticate']

i just want to login and create a defect to start the project can you please advise me how to do it 

I tried so many ways using xml/json with several languages(python,php,js) but not able to get Lw-sso.

**Comment by vkosuri** [comment]
The problem with your login credentials, did you tried manually to login?

**Comment by senthilnathang** [comment]
i tried manually in browser working fine .

**Comment by vkosuri** [comment]
which version ALM are you using

**Comment by senthilnathang** [comment]
check attachments
![shot2](https://cloud.githubusercontent.com/assets/7299075/22863193/b5906ef6-f161-11e6-9610-279651c6186d.png)
 login and also rest via browser working 
![shot1](https://cloud.githubusercontent.com/assets/7299075/22863190/aa09075a-f161-11e6-9769-2322b7aba48b.png)

**Comment by senthilnathang** [comment]
HP ALM 12.50

**Comment by vkosuri** [comment]
I am look into 12.50 API, will update it soon

**Comment by vkosuri** [comment]
can you provide printed information?

```Python
import requests
from requests.auth import HTTPBasicAuth
session = requests.session()
username='xx'
password='xxx'
base_url ='https://almalm1250saastrial.saas.hpe.com/qcbin/api/authentication/sign-in'
domain='DEFAULT_773497139'
project='773497139_DEMO'
r = session.post(base_url,auth=HTTPBasicAuth(username,password), verify=False)
print(r.text)
print(r.headers)
print(r.status_code)
```

**Comment by senthilnathang** [comment]
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 403 Forbidden</title>
</head>
<body><h2>HTTP ERROR 403</h2>
<p>Problem accessing /qcbin/api/authentication/sign-in. Reason:
<pre>    Forbidden</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>

CaseInsensitiveDict({'content-length': '316', 'set-cookie': 'JSESSIONID=h1h1p77kpv0sy5i6d6yutczo;Path=/qcbin;HttpOnly, secured_cookie=!3zAGhtDaKcjv7jp+7ayQKf2kXFbCXKdnUQtq2tJBmQG019yA0pppT3+jNgQe/9cDn57b5rnXcbtj8LGXW+0WSh7Tz4hJU6oCm3J1+iW0R/gl; path=/', 'server': 'Jetty(9.1.4.v20140401)', 'cache-control': 'must-revalidate,no-cache,no-store', 'date': 'Sun, 12 Feb 2017 17:46:24 GMT', 'content-type': 'text/html; charset=ISO-8859-1'})
403


------------------
(program exited with code: 0)
Press return to continue

**Comment by vkosuri** [comment]
403, Your credentials are wrong, did you verified?

**Comment by senthilnathang** [comment]
yes verified credentials are correct ones 
bornspy@gmail.com
Zse4$rfV

**Comment by senthilnathang** [comment]
even in browser with cookies n logged in it's forbidden
![shot3](https://cloud.githubusercontent.com/assets/7299075/22864723/833c8d02-f17c-11e6-8d47-009d248635ce.png)

**Comment by vkosuri** [comment]
@senthilnathang i would suggest check with your IT admin, is possible can you get exact REST API for ALM 12.50?

**Comment by senthilnathang** [comment]
it's free server for demo  so no support from HP at all

**Comment by senthilnathang** [comment]
any suggestion ?

**Comment by vkosuri** [comment]
Nop

**Comment by vkosuri** [comment]
My guess LWSSO is available for only crop user only.

**Comment by senthilnathang** [comment]
i think i m near can you check this code and suggest me for any fix 

> import requests
> import base64
> from requests.auth import HTTPBasicAuth
> session = requests.session()
> username='bornspy@gmail.com'
> password='Zse4$rfV'
> base_url ='http://almalm1250saastrial.saas.hpe.com:80/qcbin/'
> domain='DEFAULT_773497139'
> project='773497139_DEMO'
> 
> headers = {'Content-Type' : 'application/xml'}
> headers["Accept"] = 'application/xml'
> #~ headers["Authorization"]="Basic " + base64.b64encode(username + ':' + password)
> #~ headers['www-authenticate']='https://almalm1250saastrial.saas.hpe.com/qcbin'
> login_url = base_url + 'authentication-point/authenticate'
> #~ login_url = base_url + 'api/authentication/sign-in'
> authurl = base_url + 'rest/is-authenticated'
> req= requests.get(authurl, headers=headers, verify=False)
> print req.headers
> data = """
>         <?xml version='1.0' encoding='utf-8'?>
>         <alm-authentication>
>             <user>bornspy@gmail.com</user>
>             <password>Zse4$rfV</password>
> 	    </alm-authentication>
>         """
> lwssocookie = req.headers['WWW-Authenticate']
> headers = {'Cookie' : lwssocookie}
> headers["Accept"] = 'application/xml'
> headers["Authorization"]="Basic " + base64.b64encode(username + ':' + password)
> resp = requests.get(login_url, headers=headers,  verify=False)
> qc_session = resp.headers['Set-Cookie']
> cookie = ";".join((lwssocookie, qc_session))
> headers = {'content-type' : 'application/xml'}
> headers['accept'] = 'application/xml'
> headers['cookie'] = cookie
> #~ resp = requests.post(login_url,headers=req.headers, data=data,verify=False)
> print resp.headers,headers
> print resp.status_code
> #~ print resp.text
> 
> url = base_url + 'rest/domains/' + domain + '/projects/' + project + "?login-form-required=y"
> response = requests.get(url,  headers=headers)
> print response.text

**Comment by senthilnathang** [comment]
i think i m near to fix can you suggest me any idea to fix

import requests
import base64
from requests.auth import HTTPBasicAuth
session = requests.session()
username='bornspy@gmail.com'
password='Zse4$rfV'
base_url ='http://almalm1250saastrial.saas.hpe.com:80/qcbin/'
domain='DEFAULT_773497139'
project='773497139_DEMO'

headers = {'Content-Type' : 'application/xml'}
headers["Accept"] = 'application/xml'
#~ headers["Authorization"]="Basic " + base64.b64encode(username + ':' + password)
#~ headers['www-authenticate']='https://almalm1250saastrial.saas.hpe.com/qcbin'
login_url = base_url + 'authentication-point/authenticate'
authurl = base_url + 'rest/is-authenticated'
req= requests.get(authurl, headers=headers, verify=False)
print req.headers

lwssocookie = req.headers['WWW-Authenticate']
headers = {'Cookie' : lwssocookie}
headers["Accept"] = 'application/xml'
headers["Authorization"]="Basic " + base64.b64encode(username + ':' + password)
resp = requests.get(login_url, headers=headers,  verify=False)
qc_session = resp.headers['Set-Cookie']
cookie = ";".join((lwssocookie, qc_session))
headers = {'content-type' : 'application/xml'}
headers['accept'] = 'application/xml'
headers['cookie'] = cookie
#~ resp = requests.post(login_url,headers=req.headers, data=data,verify=False)
print resp.headers,headers
print resp.status_code
#~ print resp.text

url = base_url + 'rest/domains/' + domain + '/projects/' + project + "?login-form-required=y"
response = requests.get(url,  headers=headers)
print response.text

**Comment by vkosuri** [comment]
Did you tried, is it working? Try to get any defects, It seems to me your are getting session ids from HP ALM and not getting LWSSO cookies

**Comment by senthilnathang** [comment]
yes,don't know how to fix this and curious 

check out these screenshots too
![hpqc-issue](https://cloud.githubusercontent.com/assets/7299075/22916915/b43d0054-f2a7-11e6-89ff-ea5a7cd434f9.png)
![almerror](https://cloud.githubusercontent.com/assets/7299075/22916916/b440ab6e-f2a7-11e6-9eb0-32faeac0f76b.png)

**Comment by vkosuri** [comment]
What's your thoughts on blog post?

**Comment by maklaut** [comment]
```
cookie = ";".join((lwssocookie, qc_session))
...
headers['cookie'] = cookie
```
This code is totally wrong!
Use requests session object instead of manual cookies handling:
```
s = requests.Session()
resp = s.get(uri, ...)
...
```

**Comment by vkosuri** [comment]
@maklaut Thank you, always welcome suggestions/comments, if possible could you please update your suggestion with a Pull Request?
